### ISSUE TITLE
Grid - Wrong Math

### ISSUE THREAD

**Issue by bukinoshita** [paullonorato/norato-framework#2]
No margin-right on desktop view, when decreases the page size it shows a space on the last child.

The margin-right should be `2%` since the grids sizes is `49%` and not `1.05263%`

Desktop View:
![screenshot 2015-08-18 13 31 32](https://cloud.githubusercontent.com/assets/6929565/9336079/fd425112-45ad-11e5-8827-aacb87c6da15.png)

Tablet View:
![screenshot 2015-08-18 13 31 37](https://cloud.githubusercontent.com/assets/6929565/9336085/07829ea2-45ae-11e5-81ab-371aa8a37b7d.png)

**Comment by paullonorato** [comment]
Yeah!!! I know it... rs
I dont modify this project a long time ago =/

Tks for all _-_
